"""Adiciona campos imagem e link

Revision ID: f1d9e2f035fb
Revises: 
Create Date: 2025-05-22 08:37:22.987692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d9e2f035fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('link', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.drop_column('link')
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
